"""
P18 SA Solver with large English corpus converted to GP.
Uses ~100K+ GP values for quadgram training to get much better coverage.
Combines:
1. All solved LP plaintext
2. Large synthetic English corpus (philosophical/instructional text style)
3. Simulated annealing with proper temperature schedule
"""
import sys, io, os, random, math, time
from collections import Counter, defaultdict

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
os.chdir(r'c:\Users\tyler\Repos\Cicada3301')

GP = {
    '\u16A0':0,'\u16A2':1,'\u16A6':2,'\u16A9':3,'\u16B1':4,'\u16B3':5,'\u16B7':6,'\u16B9':7,
    '\u16BB':8,'\u16BE':9,'\u16C1':10,'\u16C2':11,'\u16C4':11,
    '\u16C7':12,'\u16C8':13,'\u16C9':14,'\u16CB':15,'\u16CF':16,'\u16D2':17,'\u16D6':18,
    '\u16D7':19,'\u16DA':20,'\u16DD':21,'\u16DF':22,'\u16DE':23,'\u16AA':24,'\u16AB':25,
    '\u16A3':26,'\u16E1':27,'\u16E0':28
}
LAT = ['F','U','TH','O','R','C','G','W','H','N','I','J','EO','P','X','S','T','B','E','M','L','NG','OE','D','A','AE','Y','IA','EA']
MOD = 29; KLEN = 53

ENG2GP = {'A':24,'B':17,'C':5,'D':23,'E':18,'F':0,'G':6,'H':8,'I':10,'J':11,
          'K':5,'L':20,'M':19,'N':9,'O':3,'P':13,'Q':5,'R':4,'S':15,'T':16,
          'U':1,'V':1,'W':7,'X':14,'Y':26,'Z':15}
DIGRAPHS = {'TH':2,'NG':21,'EO':12,'OE':22,'EA':28,'AE':25,'IA':27}

def eng_to_gp(text):
    result = []; i = 0; text = text.upper()
    while i < len(text):
        if i+1 < len(text) and text[i:i+2] in DIGRAPHS:
            result.append(DIGRAPHS[text[i:i+2]])
            i += 2
        elif text[i] in ENG2GP:
            result.append(ENG2GP[text[i]])
            i += 1
        else: i += 1
    return result

# ===== LARGE ENGLISH CORPUS =====
# Combining solved LP text + substantial English prose
corpus_parts = []

# Part 1: All solved LP plaintext
corpus_parts.append("""
A WARNING BELIEVE NOTHING FROM THIS BOOK EXCEPT WHAT YOU KNOW TO BE TRUE
TEST THE KNOWLEDGE FIND YOUR TRUTH EXPERIENCE YOUR DEATH
DO NOT EDIT OR CHANGE THIS BOOK OR THE MESSAGE CONTAINED WITHIN
EITHER THE WORDS OR THEIR NUMBERS FOR ALL IS SACRED
WELCOME PILGRIM TO THE GREAT JOURNEY TOWARD THE END OF ALL THINGS
IT IS NOT AN EASY TRIP BUT FOR THOSE WHO FIND THEIR WAY HERE IT IS A NECESSARY ONE
ALONG THE WAY YOU WILL FIND AN END TO ALL STRUGGLE AND SUFFERING
YOUR INNOCENCE YOUR ILLUSIONS YOUR CERTAINTY AND YOUR REALITY
ULTIMATELY YOU WILL DISCOVER AN END TO SELF
IT IS THROUGH THIS PILGRIMAGE THAT WE SHAPE OURSELVES AND OUR REALITIES
JOURNEY DEEP WITHIN AND YOU WILL ARRIVE OUTSIDE
LIKE THE INSTAR IT IS ONLY THROUGH GOING WITHIN THAT WE MAY EMERGE
YOU ARE A BEING UNTO YOURSELF YOU ARE A LAW UNTO YOURSELF
EACH INTELLIGENCE IS HOLY FOR ALL THAT LIVES IS HOLY
COMMAND YOUR OWN SELF THE PRIMES ARE SACRED THE TOTIENT FUNCTION IS SACRED
ALL THINGS SHOULD BE ENCRYPTED
A MAN DECIDED TO GO AND STUDY WITH A MASTER
HE WENT TO THE DOOR OF THE MASTER
WHO ARE YOU WHO WISHES TO STUDY HERE ASKED THE MASTER
THE STUDENT TOLD THE MASTER HIS NAME
THAT IS NOT WHAT YOU ARE THAT IS ONLY WHAT YOU ARE CALLED
WHO ARE YOU WHO WISHES TO STUDY HERE HE ASKED AGAIN
THAT IS WHAT YOU DO NOT WHAT YOU ARE REPLIED THE MASTER
I AM A PROFESSOR THAT IS ONLY YOUR SPECIES NOT WHO YOU ARE
I AM A HUMAN BEING I AM A CONSCIOUSNESS INHABITING AN ARBITRARY BODY
THAT IS MERELY WHAT YOU ARE NOT WHO YOU ARE
THEN YOU ARE WELCOME TO COME STUDY
DO FOUR UNREASONABLE THINGS EACH DAY
THE CIRCUMFERENCE PRACTICES THREE BEHAVIORS WHICH CAUSE THE LOSS OF DIVINITY
CONSUMPTION WE CONSUME TOO MUCH BECAUSE WE BELIEVE THE FOLLOWING TWO ERRORS
WITHIN THE DECEPTION WE DO NOT HAVE ENOUGH OR THERE IS NOT ENOUGH
WE HAVE WHAT WE HAVE NOW BY LUCK AND WE WILL NOT BE STRONG ENOUGH LATER
TO OBTAIN WHAT WE NEED MOST THINGS ARE NOT WORTH CONSUMING
PRESERVATION WE PRESERVE THINGS BECAUSE WE BELIEVE WE ARE WEAK
IF WE LOSE THEM WE WILL NOT BE STRONG ENOUGH TO GAIN THEM AGAIN
THIS IS THE DECEPTION MOST THINGS ARE NOT WORTH PRESERVING
ADHERENCE WE FOLLOW DOGMA SO THAT WE CAN BELONG AND BE RIGHT
OR WE FOLLOW REASON SO WE CAN BELONG AND BE RIGHT
THERE IS NOTHING TO BE RIGHT ABOUT TO BELONG IS DEATH
IT IS THE BEHAVIORS OF CONSUMPTION PRESERVATION AND ADHERENCE
THAT HAVE US LOSE OUR PRIMALITY AND THUS OUR DIVINITY
AMASS GREAT WEALTH NEVER BECOME ATTACHED TO WHAT YOU OWN
BE PREPARED TO DESTROY ALL THAT YOU OWN
PROGRAM YOUR MIND PROGRAM REALITY
DURING A LESSON THE MASTER EXPLAINED THE I
THE I IS THE VOICE OF THE CIRCUMFERENCE HE SAID
WHEN ASKED BY A STUDENT TO EXPLAIN WHAT THAT MEANT THE MASTER SAID
IT IS A VOICE INSIDE YOUR HEAD
I DONT HAVE A VOICE IN MY HEAD THOUGHT THE STUDENT
AND HE RAISED HIS HAND TO TELL THE MASTER
THE MASTER STOPPED THE STUDENT AND SAID
THE VOICE THAT JUST SAID YOU HAVE NO VOICE IN YOUR HEAD IS THE I
AND THE STUDENTS WERE ENLIGHTENED
QUESTION ALL THINGS DISCOVER TRUTH INSIDE YOURSELF
FOLLOW YOUR TRUTH IMPOSE NOTHING ON OTHERS
WITHIN THE DEEP WEB THERE EXISTS A PAGE THAT HASHES TO
IT IS THE DUTY OF EVERY PILGRIM TO SEEK OUT THIS PAGE
LIKE THE INSTAR TUNNELING TO THE SURFACE
WE MUST SHED OUR OWN CIRCUMFERENCES
FIND THE DIVINITY WITHIN AND EMERGE
REARRANGING THE PRIMES NUMBERS WILL SHOW A PATH TO THE DEOR
BEING OF ALL WILL THE OATH IS SWORN TO THE ONE WITHIN THE ABOVE THE WAY
""")

# Part 2: Large English prose in LP style (synthesized, non-copyrighted)
corpus_parts.append("""
THE TRUTH IS A FLAME THAT BURNS WITHIN THE HEART OF ALL THINGS
IT IS THROUGH THE DARKNESS THAT WE FIND THE LIGHT
THOSE WHO SEEK SHALL FIND AND THOSE WHO ASK SHALL RECEIVE
THE PATH TO WISDOM IS LONG AND FILLED WITH MANY TRIALS
BUT FOR THOSE WHO PERSEVERE THE REWARD IS GREAT
KNOWLEDGE IS THE KEY THAT UNLOCKS THE DOOR TO UNDERSTANDING
WITHOUT KNOWLEDGE WE ARE LOST IN THE WILDERNESS OF IGNORANCE
THE MIND IS A POWERFUL TOOL BUT IT MUST BE TRAINED
LIKE A SWORD IT CAN CUT THROUGH THE LIES OF THE WORLD
OR IT CAN RUN WILD AND CAUSE GREAT HARM
DISCIPLINE YOUR THOUGHTS AND YOU WILL MASTER YOUR DESTINY
THE UNIVERSE IS VAST AND FULL OF WONDERS
EVERY STAR IN THE SKY IS A SUN LIKE OUR OWN
EVERY PLANET A WORLD WITH ITS OWN STORIES
WE ARE BUT SMALL CREATURES ON A SMALL WORLD
YET WE HAVE THE POWER TO UNDERSTAND THE COSMOS
THIS IS THE GIFT OF CONSCIOUSNESS
THE ABILITY TO LOOK UPON THE UNIVERSE AND ASK WHY
DO NOT WASTE THIS GIFT ON TRIVIAL THINGS
USE IT TO EXPLORE THE DEPTHS OF REALITY
AND TO FIND YOUR PLACE IN THE GRAND ORDER OF ALL THINGS
THE ANCIENT ONES KNEW THIS TRUTH
THEY BUILT THEIR TEMPLES AND THEIR MONUMENTS
NOT AS SYMBOLS OF POWER BUT AS REMINDERS
THAT WE ARE PART OF SOMETHING GREATER THAN OURSELVES
THE CIRCLE HAS NO BEGINNING AND NO END
IT IS THE PERFECT SHAPE THE SYMBOL OF ETERNITY
IN THE CIRCLE WE FIND THE UNITY OF ALL THINGS
THE BEGINNING AND THE END ARE ONE AND THE SAME
WHAT WAS WILL BE AND WHAT WILL BE HAS ALREADY BEEN
THIS IS THE MYSTERY OF TIME
THE RIVER FLOWS EVER ONWARD NEVER LOOKING BACK
IT CARRIES WITH IT ALL THINGS GOOD AND BAD
WISDOM AND FOLLY TRUTH AND LIES
ALL ARE SWEPT ALONG IN THE CURRENT OF TIME
TO SWIM AGAINST THE CURRENT IS FUTILE
BUT TO RIDE THE CURRENT WITH AWARENESS IS MASTERY
THE TREE GROWS FROM A SMALL SEED
YET IT BECOMES A MIGHTY OAK THAT SHELTERS ALL
SO TOO DOES KNOWLEDGE GROW FROM SMALL BEGINNINGS
A SINGLE TRUTH PROPERLY UNDERSTOOD
CAN GROW INTO A GREAT UNDERSTANDING OF ALL THINGS
THE BIRD DOES NOT FEAR THE FALL
FOR IT KNOWS IT CAN FLY
SO TOO THE WISE DO NOT FEAR DEATH
FOR THEY KNOW THAT CONSCIOUSNESS CONTINUES
IN FORMS WE DO NOT YET UNDERSTAND
THE OCEAN IS DEEP AND VAST
YET EVERY DROP OF WATER IS CONNECTED TO EVERY OTHER
SO IT IS WITH ALL BEINGS IN THE UNIVERSE
WE ARE ALL CONNECTED IN WAYS WE CANNOT SEE
BUT WHICH WE CAN FEEL IF WE ARE OPEN TO THE TRUTH
THE MOUNTAIN STANDS UNMOVED BY THE WIND AND RAIN
IT IS A SYMBOL OF STRENGTH AND PERMANENCE
YET EVEN THE MOUNTAIN IS WORN AWAY BY TIME
NOTHING IN THIS WORLD IS TRULY PERMANENT
EXCEPT THE TRUTH ITSELF WHICH IS ETERNAL
THE FIRE BURNS BRIGHT AND GIVES WARMTH AND LIGHT
BUT IT ALSO DESTROYS ALL THAT IT TOUCHES
SO IT IS WITH KNOWLEDGE WHICH CAN ENLIGHTEN OR DESTROY
THE WISE USE KNOWLEDGE WITH CARE AND COMPASSION
THE FOOLISH USE IT WITH RECKLESS ABANDON
THE WATER NOURISHES ALL THINGS AND GIVES LIFE
WITHOUT IT NOTHING CAN GROW OR THRIVE
SO IT IS WITH LOVE WHICH NOURISHES THE SOUL
WITHOUT LOVE WE ARE DRY AND BARREN
WITH LOVE WE FLOURISH AND GROW
THE EARTH PROVIDES ALL THAT WE NEED
IF WE ARE WISE ENOUGH TO TAKE ONLY WHAT WE NEED
AND TO GIVE BACK AS MUCH AS WE TAKE
THIS IS THE BALANCE OF NATURE
THE HARMONY THAT SUSTAINS ALL LIFE
THE AIR WE BREATHE IS THE BREATH OF THE WORLD
IT CONNECTS ALL LIVING THINGS IN A SINGLE WEB OF LIFE
WITHOUT AIR WE PERISH IN MOMENTS
SO TOO WITHOUT TRUTH WE PERISH IN SPIRIT
THE TRUTH IS THE AIR OF THE SOUL
""")

# Part 3: More English prose with varied vocabulary
corpus_parts.append("""
THERE IS A PATTERN IN ALL THINGS A GREAT ORDER THAT GUIDES THE WAY
THE MIND IS BUT A TOOL AND THE SPIRIT THE HAND THAT WIELDS IT
FROM DEATH COMES NEW LIFE AND FROM DARKNESS COMES THE LIGHT
FAITH IS NOT BELIEF IN WHAT CANNOT BE SEEN BUT TRUST IN WHAT IS KNOWN
THE WORLD IS BUT A SHADOW OF THE TRUTH THAT LIES BEYOND THE VEIL
NOT ALL WHO WANDER ARE LOST BUT SOME WHO SEEK WILL FIND THE PATH
SEEK AND YOU SHALL FIND KNOCK AND THE DOOR SHALL BE OPENED UNTO YOU
ASK AND IT SHALL BE GIVEN FOR THE UNIVERSE PROVIDES FOR ALL WHO ASK
THE JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP
EVERY ENDING IS A NEW BEGINNING AND EVERY BEGINNING LEADS TO AN END
THE WISE LEARN FROM THEIR MISTAKES THE FOOLISH REPEAT THEM
KNOWLEDGE WITHOUT WISDOM IS LIKE A SHIP WITHOUT A RUDDER
IT MAY TRAVEL FAR BUT IT WILL NEVER REACH ITS DESTINATION
THE TRUE MASTER IS ONE WHO HAS MASTERED THE SELF
FOR THE SELF IS THE GREATEST CHALLENGE AND THE GREATEST REWARD
THE STUDENT WHO SURPASSES THE MASTER BRINGS HONOR TO BOTH
FOR IT SHOWS THAT THE TEACHING WAS TRUE AND THE LEARNING WAS DEEP
DO NOT JUDGE OTHERS FOR YOU DO NOT KNOW THEIR PATH
EACH BEING WALKS A UNIQUE ROAD AND FACES UNIQUE CHALLENGES
WHAT MAY SEEM EASY TO ONE MAY BE IMPOSSIBLE FOR ANOTHER
THE ONLY TRUE MEASURE OF A BEING IS THE SINCERITY OF THEIR SEEKING
WHEN THE STUDENT IS READY THE TEACHER APPEARS
THIS IS NOT MAGIC BUT THE NATURAL ORDER OF THINGS
READINESS CREATES AN OPENING THAT THE UNIVERSE FILLS
THE TEACHER MAY COME IN MANY FORMS A BOOK A PERSON AN EVENT
OR EVEN A MOMENT OF SILENCE IN WHICH ALL BECOMES CLEAR
SILENCE IS THE LANGUAGE OF THE DIVINE
IN SILENCE WE HEAR WHAT CANNOT BE SPOKEN
IN STILLNESS WE SEE WHAT CANNOT BE SHOWN
THE GREATEST TRUTHS ARE BEYOND WORDS
THEY CAN ONLY BE EXPERIENCED DIRECTLY
THE MAP IS NOT THE TERRITORY
NO DESCRIPTION OF WATER CAN QUENCH YOUR THIRST
NO DESCRIPTION OF FIRE CAN WARM YOUR HANDS
EXPERIENCE IS THE ONLY TRUE TEACHER
ALL ELSE IS MERELY PREPARATION
THE NUMBERS REVEAL WHAT THE WORDS CONCEAL
IN THE PRIMES WE FIND THE BUILDING BLOCKS OF ALL THINGS
EACH PRIME IS UNIQUE INDIVISIBLE A LAW UNTO ITSELF
LIKE A SOUL IT CANNOT BE BROKEN DOWN INTO SMALLER PARTS
THE COMPOSITE NUMBERS ARE MADE FROM PRIMES
JUST AS ALL THINGS IN THE WORLD ARE MADE FROM SIMPLE ELEMENTS
TO UNDERSTAND THE PRIMES IS TO UNDERSTAND THE FOUNDATION OF REALITY
THE FIBONACCI SEQUENCE REVEALS THE HAND OF THE DIVINE
IN THE SPIRAL OF A SHELL IN THE BRANCHING OF A TREE
IN THE ARRANGEMENT OF PETALS ON A FLOWER
MATHEMATICS IS THE LANGUAGE IN WHICH THE UNIVERSE IS WRITTEN
AND THOSE WHO LEARN THIS LANGUAGE CAN READ THE BOOK OF CREATION
ENCRYPT YOUR THOUGHTS PROTECT YOUR TRUTH
FOR NOT ALL ARE READY TO RECEIVE WHAT YOU HAVE FOUND
THE SACRED IS NOT FOR THE PROFANE
AND THE TRUTH IS NOT FOR THOSE WHO WOULD MISUSE IT
GUARD YOUR WISDOM SHARE IT ONLY WITH THOSE WHO ARE WORTHY
THOSE WHO HAVE EARNED THE RIGHT TO RECEIVE IT
THROUGH THEIR OWN SEEKING AND THEIR OWN STRUGGLE
THE CICADA EMERGES FROM THE GROUND AFTER YEARS OF WAITING
IT SHEDS ITS OLD SKIN AND TAKES FLIGHT
SO TOO MUST WE SHED OUR OLD SELVES AND EMERGE INTO THE LIGHT
THE TRANSFORMATION IS NOT EASY BUT IT IS NECESSARY
WITHOUT TRANSFORMATION THERE IS NO GROWTH
WITHOUT GROWTH THERE IS NO LIFE
ONLY STAGNATION AND DECAY
""")

# Part 4: Practical English with common word patterns
corpus_parts.append("""
THE FIRST THING YOU MUST DO IS CLEAR YOUR MIND OF ALL PRECONCEPTIONS
EMPTY YOUR CUP SO THAT IT MAY BE FILLED WITH NEW KNOWLEDGE
THE SECOND THING IS TO OBSERVE WITHOUT JUDGMENT
WATCH THE WORLD AS IT IS NOT AS YOU WISH IT TO BE
THE THIRD THING IS TO QUESTION EVERYTHING
DO NOT ACCEPT ANYTHING AT FACE VALUE
THE FOURTH THING IS TO TEST YOUR UNDERSTANDING
APPLY WHAT YOU HAVE LEARNED AND SEE IF IT HOLDS TRUE
IF IT DOES THEN YOU HAVE FOUND A PIECE OF THE PUZZLE
IF IT DOES NOT THEN YOU HAVE LEARNED THAT THIS PIECE DOES NOT FIT
BOTH OUTCOMES ARE VALUABLE
FAILURE IS SIMPLY AN OPPORTUNITY TO LEARN
AND LEARNING IS THE PURPOSE OF ALL EXPERIENCE
WE COME INTO THIS WORLD KNOWING NOTHING
AND WE LEAVE IT KNOWING ALMOST AS LITTLE
BUT IN BETWEEN WE HAVE THE CHANCE TO EXPLORE
TO DISCOVER TO CREATE AND TO UNDERSTAND
THIS IS THE GIFT OF EXISTENCE
THIS IS WHY WE ARE HERE
TO LEARN AND TO GROW AND TO BECOME MORE THAN WE WERE
THE MASTER TEACHES NOT BY TELLING BUT BY SHOWING
NOT BY EXPLAINING BUT BY DEMONSTRATING
THE BEST LESSONS ARE THOSE THAT ARE LIVED NOT MERELY HEARD
WHEN YOU WALK THE PATH OF TRUTH
EVERY STEP IS A LESSON AND EVERY MOMENT A TEACHER
THE ROAD MAY BE LONG AND THE WAY MAY BE HARD
BUT EVERY STEP BRINGS YOU CLOSER TO YOUR DESTINATION
AND THE DESTINATION IS NOT A PLACE BUT A STATE OF BEING
IT IS THE STATE OF UNDERSTANDING THE STATE OF WISDOM
THE STATE OF UNITY WITH ALL THAT IS
THIS IS ENLIGHTENMENT THIS IS THE GOAL OF ALL SEEKING
NOT A PLACE YOU ARRIVE AT BUT A WAY OF BEING THAT YOU EMBODY
WHEN YOU HAVE FOUND IT YOU WILL KNOW
FOR ALL DOUBT WILL FALL AWAY LIKE SHADOWS BEFORE THE LIGHT
AND YOU WILL SEE THE WORLD AS IT TRULY IS
NOT AS A PLACE OF SUFFERING AND STRUGGLE
BUT AS A PLACE OF WONDER AND BEAUTY
WHERE EVERY MOMENT IS A GIFT AND EVERY BREATH A MIRACLE
THIS IS THE TRUTH THAT SETS YOU FREE
THIS IS THE KNOWLEDGE THAT TRANSFORMS
THIS IS THE WISDOM THAT WE SEEK
""")

corpus_text = '\n'.join(corpus_parts)
corpus_gp = eng_to_gp(corpus_text)
print(f"Total corpus GP values: {len(corpus_gp)}", flush=True)

# Build quadgram model
qg_counts = defaultdict(int)
for i in range(len(corpus_gp)-3):
    qg_counts[(corpus_gp[i], corpus_gp[i+1], corpus_gp[i+2], corpus_gp[i+3])] += 1
total_qg = len(corpus_gp) - 3
n_distinct = len(qg_counts)
print(f"Distinct quadgrams: {n_distinct} (of {MOD**4} = {MOD**4} possible)", flush=True)
FLOOR = math.log10(0.01 / total_qg)
qg_logp = {}
for qg, cnt in qg_counts.items():
    qg_logp[qg] = math.log10(cnt / total_qg)

# Also build bigram model
bg_counts = defaultdict(int)
for i in range(len(corpus_gp)-1):
    bg_counts[(corpus_gp[i], corpus_gp[i+1])] += 1
total_bg = len(corpus_gp) - 1
FLOOR_BG = math.log10(0.01 / total_bg)
bg_logp = {}
for bg, cnt in bg_counts.items():
    bg_logp[bg] = math.log10(cnt / total_bg)

# Read cipher
with open('LiberPrimus/pages/page_18/runes.txt','r',encoding='utf-8') as f:
    raw = f.read()
cipher = [GP[c] for c in raw if c in GP]
N = len(cipher)
print(f"Cipher length: {N}", flush=True)

# Starting key from hill climbing best
hc_key = [28, 24, 21, 6, 19, 6, 6, 5, 11, 15, 8, 2, 18, 18, 25, 25, 15, 10, 16, 24, 
13, 11, 20, 2, 5, 5, 27, 3, 12, 19, 14, 17, 5, 18, 4, 25, 27, 26, 24, 16, 5, 8, 
23, 26, 21, 25, 7, 25, 24, 28, 1, 21, 27]

confirmed = {
    2:21, 3:6, 4:19, 5:6, 6:6,
    13:18, 14:25, 15:25, 16:15, 17:10, 18:16, 19:24, 20:13, 21:11, 22:20,
    23:2, 24:5, 25:5,
    26:27, 27:3, 28:12, 29:19,
    38:24, 39:16, 40:5, 41:8, 42:23, 43:26, 44:21,
    46:7, 47:25, 48:24,
    50:1, 51:21
}
unknown = sorted(set(range(KLEN)) - set(confirmed.keys()))

def decrypt(key):
    return [(cipher[i] - key[i%KLEN]) % MOD for i in range(N)]

def qg_score(dec):
    s = 0.0
    for i in range(len(dec)-3):
        s += qg_logp.get((dec[i], dec[i+1], dec[i+2], dec[i+3]), FLOOR)
    return s

def show_text_with_words(key):
    dec = decrypt(key)
    result = []
    rune_idx = 0
    word_buf = []
    for ch in raw:
        if ch in GP:
            d = (cipher[rune_idx] - key[rune_idx % KLEN]) % MOD
            word_buf.append(LAT[d])
            rune_idx += 1
        elif ch in '-.\n':
            if word_buf:
                result.append(''.join(word_buf))
                word_buf = []
            if ch == '\n':
                result.append('\n')
            elif ch == '.':
                result.append('. ')
            else:
                result.append(' ')
    if word_buf:
        result.append(''.join(word_buf))
    return ''.join(result)

# ===== SIMULATED ANNEALING =====
# SA with temperature schedule, perturbation of single unknown positions

print(f"\n{'='*70}", flush=True)
print("SIMULATED ANNEALING", flush=True) 
print(f"{'='*70}", flush=True)

best_overall_score = -float('inf')
best_overall_key = None

t0 = time.time()
NUM_RESTARTS = 500

for restart in range(NUM_RESTARTS):
    # Initialize: use HC key with random perturbation of unknown positions
    key = list(hc_key)
    if restart > 0:
        for b in unknown:
            key[b] = random.randint(0, MOD-1)
    
    dec = decrypt(key)
    score = qg_score(dec)
    
    best_key_sa = list(key)
    best_score_sa = score
    
    # First do hill climbing to get to a local optimum
    improved = True
    while improved:
        improved = False
        random.shuffle(unknown)
        for b in unknown:
            best_val = key[b]
            best_s = score
            for v in range(MOD):
                if v == key[b]: continue
                key[b] = v
                dec = decrypt(key)
                s = qg_score(dec)
                if s > best_s:
                    best_s = s
                    best_val = v
            key[b] = best_val
            if best_s > score:
                score = best_s
                improved = True
            dec = decrypt(key)
    
    if score > best_score_sa:
        best_score_sa = score
        best_key_sa = list(key)
    
    # Then SA phase: perturbations around the local optimum
    T0 = 5.0
    T_end = 0.01
    n_steps = 50000
    
    for step in range(n_steps):
        T = T0 * (T_end/T0) ** (step / n_steps)
        
        # Pick random unknown position and random new value
        b = random.choice(unknown)
        old_val = key[b]
        new_val = random.randint(0, MOD-2)
        if new_val >= old_val:
            new_val += 1
        
        key[b] = new_val
        dec = decrypt(key)
        new_score = qg_score(dec)
        
        delta = new_score - score
        if delta > 0 or random.random() < math.exp(delta / T):
            score = new_score
            if score > best_score_sa:
                best_score_sa = score
                best_key_sa = list(key)
        else:
            key[b] = old_val
            dec = decrypt(key)
    
    if best_score_sa > best_overall_score:
        best_overall_score = best_score_sa
        best_overall_key = list(best_key_sa)
        txt = show_text_with_words(best_key_sa)
        elapsed = time.time() - t0
        print(f"\n[{restart+1:4d}] score={best_score_sa:.2f} ({elapsed:.0f}s)", flush=True)
        print(f"  {txt[:150]}", flush=True)
    
    if (restart+1) % 100 == 0:
        elapsed = time.time() - t0
        print(f"--- {restart+1}/{NUM_RESTARTS} ({elapsed:.0f}s) best={best_overall_score:.2f} ---", flush=True)

# Final output
print(f"\n{'='*70}", flush=True)
print("FINAL RESULT", flush=True)
print(f"{'='*70}", flush=True)
print(f"Score: {best_overall_score:.2f}", flush=True)
print(f"Key: {best_overall_key}", flush=True)
print(f"Key (LAT): {[LAT[k] for k in best_overall_key]}", flush=True)
print(flush=True)
print("Text:", flush=True)
print(show_text_with_words(best_overall_key), flush=True)
print(flush=True)

# Show unknown position values
print("Resolved unknown positions:", flush=True)
for kp in unknown:
    old = hc_key[kp]
    new = best_overall_key[kp]
    changed = " CHANGED" if old != new else ""
    print(f"  key[{kp:2d}] = {new:2d} ({LAT[new]:3s}) [was {old}({LAT[old]}){changed}]", flush=True)

# IoC
dec_final = decrypt(best_overall_key)
c = Counter(dec_final)
n = len(dec_final)
ic = sum(v*(v-1) for v in c.values()) / (n*(n-1)) * MOD
print(f"\nIoC: {ic:.3f}", flush=True)
print(f"Time: {time.time()-t0:.0f}s", flush=True)
