"""Regenerate pages/page_XX/runes.txt and README.md from the canonical corpus.

    python -m tools.rebuild_page_files            # dry run (default): show what would change
    python -m tools.rebuild_page_files --write    # apply

Why this exists: until 2026-09-29 `page_N/runes.txt` held LP2 page N while `page_N/images/`
holds complete-archive scan N.jpg, so every page file disagreed with its own image.

Guards (AGENTS.md "Destructive Actions"):
  * dry-run is the default; --write is the opt-in
  * refuses to write into a folder whose images/XX.jpg is missing (wrong or unverified target)
  * every target path is asserted to be inside <root>/pages
  * refuses --write when pages/ has uncommitted changes (fails closed if git cannot answer),
    unless every target already matches — then there is nothing to do
  * logs the count written and the undo command:  git checkout HEAD -- pages/
"""

from __future__ import annotations

import argparse
import logging
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from tools.lpcore.corpus import REPO_ROOT, Corpus, load_corpus, lp_location
from tools.lpcore.gematria import RUNE_INDEX, indices_to_latin
from tools.lpcore.solved import SEGMENT_TITLES, SOLVED_BY_SEGMENT, SOLVED_SECTIONS, decrypt_section
from tools.lpcore.verify import load_translation

log = logging.getLogger("rebuild_page_files")

SCANS = range(75)
NO_RUNE_NOTES = {
    0: "LP1 title page — no runes.",
    2: "LP1 chapter title page — no runes.",
    67: "LP2 page 50 — base-60 number grid only, no runes.",
}
UNDO = "git checkout HEAD -- pages/"


class RefusedError(RuntimeError):
    """A guard refused the operation; nothing was written."""


@dataclass(frozen=True)
class PlannedWrite:
    path: Path
    new: str
    old: str | None

    @property
    def changed(self) -> bool:
        return self.old != self.new


def _assert_inside(path: Path, parent: Path) -> None:
    if not path.resolve().is_relative_to(parent.resolve()):
        raise RefusedError(f"{path} resolves outside {parent} — refusing")


def page_runes_text(corpus: Corpus, scan: int) -> str:
    page = corpus.page_by_scan(scan)
    if page is None:
        return ""
    return page.raw.strip("\n") + "\n"


def _page_rune_ranges(corpus: Corpus) -> dict[int, tuple[int, int]]:
    ranges, start = {}, 0
    for page in corpus.pages:
        n = len(page.runes)
        ranges[page.scan] = (start, start + n)
        start += n
    return ranges


def _plaintext_by_scan(corpus: Corpus, translation: dict) -> dict[int, list[str]]:
    """Verified plaintext words of solved sections, keyed by the scan each word starts on."""
    out: dict[int, list[str]] = {}
    for section in SOLVED_SECTIONS:
        plain_words, _ = decrypt_section(corpus, translation, section)
        for word, plain in zip(corpus.rune_words(section.segment), plain_words):
            out.setdefault(word.scan, []).append(indices_to_latin(plain))
    return out


def page_readme(corpus: Corpus, scan: int, plaintext: dict[int, list[str]],
                ranges: dict[int, tuple[int, int]]) -> str:
    part, number = lp_location(scan)
    page = corpus.page_by_scan(scan)
    lines = [
        f"# page_{scan:02d} — scan {scan:02d}.jpg",
        "",
        "> Generated by `python -m tools.rebuild_page_files` from `data/canonical/liber_primus_master.txt`.",
        "> Do not edit by hand — change the generator. Solved status is asserted by `tests/test_lpcore.py`.",
        "",
        "| | |",
        "|---|---|",
        f"| Book position | {part} page {number} |",
    ]
    if page is None or not page.runes:
        lines += [f"| Status | {NO_RUNE_NOTES.get(scan, 'no runes on this page')} |", ""]
    else:
        lo, hi = ranges[scan]
        segments = sorted({w.segment for w in corpus.rune_words()
                           if w.rune_offset < hi and w.rune_offset + len(w.runes) > lo})
        seg_text = "; ".join(f"{s} — {SEGMENT_TITLES[s]}" for s in segments)
        solved = [SOLVED_BY_SEGMENT[s] for s in segments if s in SOLVED_BY_SEGMENT]
        if len(solved) == len(segments):
            status = "**SOLVED** — " + "; ".join(s.description for s in solved)
        elif solved:
            status = "**PARTLY SOLVED** (page spans solved and unsolved segments)"
        else:
            status = "**UNSOLVED**"
        lines += [
            f"| Segment | {seg_text} |",
            f"| Status | {status} |",
            f"| Runes on this page | {len(page.runes)} |",
            "",
        ]
        if plaintext.get(scan):
            lines += ["## Plaintext (words beginning on this page)", "", " ".join(plaintext[scan]), ""]
    lines += [f"**Runes:** [`runes.txt`](runes.txt) · **Scan:** [`images/{scan:02d}.jpg`](images/{scan:02d}.jpg)", ""]
    return "\n".join(lines)


def plan(root: Path, corpus: Corpus, translation: dict) -> list[PlannedWrite]:
    pages_dir = root / "pages"
    plaintext = _plaintext_by_scan(corpus, translation)
    ranges = _page_rune_ranges(corpus)
    writes: list[PlannedWrite] = []
    for scan in SCANS:
        folder = pages_dir / f"page_{scan:02d}"
        _assert_inside(folder, pages_dir)
        image = folder / "images" / f"{scan:02d}.jpg"
        if not image.is_file():
            raise RefusedError(f"{image} missing — refusing to write into an unverified folder")
        for name, content in (("runes.txt", page_runes_text(corpus, scan)),
                              ("README.md", page_readme(corpus, scan, plaintext, ranges))):
            target = folder / name
            _assert_inside(target, pages_dir)
            old = target.read_text(encoding="utf-8") if target.exists() else None
            writes.append(PlannedWrite(target, content, old))
    if len(writes) != 2 * len(SCANS):
        raise RefusedError(f"planned {len(writes)} writes, expected {2 * len(SCANS)}")
    return writes


def pages_dirty(root: Path) -> bool:
    """True if git reports uncommitted changes under pages/. Fails closed."""
    try:
        result = subprocess.run(["git", "status", "--porcelain", "--", "pages"], cwd=root,
                                capture_output=True, text=True, check=True, timeout=60)
    except (OSError, subprocess.SubprocessError) as exc:
        log.error("cannot determine git status of %s/pages: %s", root, exc)
        raise RefusedError("cannot verify pages/ is committed — refusing (fail closed)") from exc
    return bool(result.stdout.strip())


def apply(writes: list[PlannedWrite], *, dirty: bool) -> int:
    changed = [w for w in writes if w.changed]
    if not changed:
        log.info("all %d targets already match the canonical corpus — nothing to do", len(writes))
        return 0
    if dirty:
        raise RefusedError("pages/ has uncommitted changes — commit or stash them first; "
                           "refusing to overwrite work that git cannot restore")
    log.info("writing %d of %d files; undo with: %s", len(changed), len(writes), UNDO)
    for w in changed:
        w.path.write_text(w.new, encoding="utf-8", newline="\n")
    log.info("wrote %d files; undo with: %s", len(changed), UNDO)
    return len(changed)


def _rune_count(text: str | None) -> int:
    return sum(1 for ch in (text or "") if ch in RUNE_INDEX)


def _summary(writes: list[PlannedWrite]) -> str:
    rows = []
    for w in writes:
        if w.path.name != "runes.txt":
            continue
        state = "unchanged" if not w.changed else ("NEW" if w.old is None else "CHANGED")
        rows.append(f"{w.path.parent.name}: {state:9} runes {_rune_count(w.old):4d} -> {_rune_count(w.new):4d}")
    return "\n".join(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="apply the changes (default is a dry run)")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="repository root")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        writes = plan(args.root, load_corpus(), load_translation())
        print(_summary(writes))
        n_changed = sum(w.changed for w in writes)
        if not args.write:
            print(f"\nDRY RUN: {n_changed} of {len(writes)} files would change. Re-run with --write to apply.")
            return 0
        apply(writes, dirty=pages_dirty(args.root))
    except RefusedError as exc:
        log.error("REFUSED: %s", exc)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
